### ISSUE TITLE
master is broken on macOS

### ISSUE THREAD

**Issue by mkhl** [ibara/mg#11]
See [the build errors on travis](https://travis-ci.org/ibara/mg/builds/147333136)

On macOS, the atime and mtime fields of `struct stat` are called `st_atimespec` and `st_mtimespec` respectively. (See [fileio.c](../blob/master/fileio.c#L272-L273).)

In addition, macOS is missing `futimens` and only supports `futimes`, which takes `const struct timeval times[2]` (instead of `const struct timespec times[2]`). Conversion between those can be done using the (provided) `TIMESPEC_TO_TIMEVAL` though. (See [fileio.c](../blob/master/fileio.c#L274).)

Adding `futimens` to `portable/apple/` seems easy but doesn't deal with the differences in `struct timespec`. Maybe it makes sense to write a wrapper around `futimes`/`futimens` that takes a `struct stat` argument?

**Comment by ibara** [comment]
Hey, so I don't own any modern Apple hardware (the newest thing I have is a PowerBook G4 from 2005 that runs OpenBSD).

I'm happy to accept any diffs you or other Mac OS people are willing to contribute but it's unlikely that I'll be able to fix these problems.

**Comment by mkhl** [comment]
My apologies, I didn’t want to seem entitled and I appreciate that you can’t fix these problems. I guess I was hoping for advice on how to fix them, but I could have stated that clearly.

After reading a bunch of man pages and a few OpenBSD headers, I was able to fix it locally and, hopefully, portably, see #12.

**Comment by ibara** [comment]
No need to apologize--I didn't read it as entitlement.
Looking at your patch now.
