### ISSUE TITLE
devio.us is down

### ISSUE THREAD

**Issue by ilovezfs** [ibara/mg#18]
The homepage seems to be on 🌴 https://devio.us/~bcallah/mg/

**Comment by ibara** [comment]
Correct.

**Comment by ilovezfs** [comment]
@ibara what should I put in the homebrew formula for the homepage for `mg`? Is it expected to come back?

**Comment by ibara** [comment]
It will return.

**Comment by ilovezfs** [comment]
@ibara OK. In the meantime, this: https://github.com/Homebrew/homebrew-core/pull/28390
