### ISSUE TITLE
broken build on MacOS <= 10.9

### ISSUE THREAD

**Issue by ra1nb0w** [ibara/mg#20]
I updated mg in macports to 20180927 and some builds failure are raised.
First of all, I read #11 #12 and one error was already present (```fstatat```) but without solution.

All errors are ```Undefined symbols```

- for 10.9,10.8,10.7 is ```_fstatat```
- for 10.6,10.5 are ```_fstatat``` ```_strndup``` ```_getline```

So, what do you think about adding patches to fix those errors? at least ```_fstatat```.
I found this [https://github.com/PixarAnimationStudios/USD/pull/139/files](commit) from Pixar that fallback to ```lstat```.

thanks

**Comment by ibara** [comment]
fstatat is either stat or lstat, depending on the flags given to it. So please check.
It probably makes sense to make fstatat a wrapper around stat or lstat. That way we don't have to alter any source code.

We can grab strndup and getline from OpenBSD.

**Comment by ibara** [comment]
I'm still not sure the best approach for fstatat yet, but strndup and getline are taken care of.

**Comment by ra1nb0w** [comment]
Oh, you are so fast. Thank you.
For fstatat we can include a function like this if the OS doesn't provide it
```c
int
fstatat(int fd, const char *path, struct stat *buf, int flag)
{
	if(flag & AT_SYMLINK_NOFOLLOW) {
		return lstat(path, buf);
	} else {
		return stat(path, buf);
	}
}
```
in this way we don't patch upstream. We need to take into account the relative path that `fstatat` introduce to stat and lstat. What do you think?

**Comment by ibara** [comment]
I just looked at the source code. The only place that uses fstatat is in fileio.c:530
if (fstatat(dirfd(dirp), dent->d_name, &statbuf, 0) < 0)
So I think we can just get away with it being a stat wrapper. I'll fix it now.

**Comment by ibara** [comment]
Fixed. Thanks for reporting. OpenBSD 6.5-beta was tagged a few days ago, so expect a new release here in about a month.

**Comment by ra1nb0w** [comment]
Thanks. In 10.6
in `getline.c` change to
```c
ssize_t *
getline(char **buf, size_t *bufsiz, FILE *fp)
```
in `configure`
```c
echo "extern char *strndup(const char *, size_t);" >> config.h
```
unfortunately 10.6 doesn't have "_strnlen" (undefined symbols)

**Comment by ibara** [comment]
Fixed.

**Comment by ra1nb0w** [comment]
Missing the fix of `strndup` on `configure`

**Comment by ibara** [comment]
Done.

**Comment by ra1nb0w** [comment]
Works. thank you so much!

**Comment by ibara** [comment]
Great!
And I have a Mac OS X 10.4.11 machine now, so it should help make macOS maintenance easier.

**Comment by ra1nb0w** [comment]
Nice ;-)

I checked compatibility with Mac OS X 10.4.11 PPC (iBook) and the following errors need to be fixed

- [ ] invalid initializer
```c
dired.c:72: error: invalid initializer
```
add to `config.h` through `configure`
```c
#define SLIST_HEAD_INITIALIZER(head) { NULL }
```
`SLIST_HEAD_INITIALIZER` doesn't exist on `sys/queue.h`

- [ ] static declaration
```c
fparseln.c:79: error: static declaration of 'fgetln' follows non-static declaration
/usr/include/stdio.h:315: error: previous declaration of 'fgetln' was here
```
`stdio.h` define `fgetln()` ifndef `_POSIX_C_SOURCE`. But declaring it doesn't work. Remove `static` works but it is bad.

- [ ] linking
```c
/usr/bin/ld: can't locate file for: -lutil
```
seems useless `-lutil` on MacOS. Tested version 10.4.11 and 10.14.3.

**Comment by ibara** [comment]
I've already got all this fixed. I'll commit it later.

**Comment by ra1nb0w** [comment]
Good. Then you can change README with `Mac OS X (10.4 or later)`. Anyway, thank your support.
