### ISSUE TITLE
Update the Freebsd ports to 6.6

### ISSUE THREAD

**Issue by lin7sh** [ibara/mg#25]
Hi
Thanks for this beautiful editor, Do you plan to update the port to the new 6.6 release?

**Comment by ibara** [comment]
The maintainer of the FreeBSD package is tobik@FreeBSD. I imagine he will do so.
Note that mg-6.6 hasn't actually been released yet; there still could be changes to mg in OpenBSD between now and the 6.6 release.

**Comment by lin7sh** [comment]
@ibara thanks for explaining this. I'm trying to put all your "openbsd based" bin utils into freebsd, they works beautifully well, Is there any other openbsd's hidden gem that you are planning to port to other platform (FreeBSD particularly)?

**Comment by ibara** [comment]
oksh is already in FreeBSD ports. Not sure what else might be super useful that I have here on GitHub that isn't in FreeBSD ports. OpenRCS maybe?

**Comment by lin7sh** [comment]
Is OpenRCS a version control tool? Openbsd's got is very promising as a version control alternative
