### ISSUE TITLE
Alpine Linux: ffwopen(): fileio.c:102:17: error: 'DEFFILEMODE' undeclared

### ISSUE THREAD

**Issue by dgoerger** [ibara/mg#26]
Thanks for this! It's nice to be able to carry aspects of my OpenBSD setup over to Linux when I have to use that platform. :)

Here's my Dockerfile build environment:

```Dockerfile
FROM alpine:latest

RUN echo "nameserver 1.1.1.1" | tee /etc/resolv.conf && \
apk add --no-cache gcc git libc-dev make libbsd-dev ncurses-dev ncurses-static && \
git clone https://github.com/ibara/mg.git /home/mg && \
cd /home/mg && \
./configure --enable-static --prefix=/usr --mandir=/usr/share/man && \
make && \
strip ./mg
```

Unfortunately it bombs out in the compilation:

```
fileio.c: In function 'ffwopen':
fileio.c:102:17: error: 'DEFFILEMODE' undeclared (first use in this function); did you mean 'EFFILE'?
  mode_t fmode = DEFFILEMODE;
                 ^~~~~~~~~~~
                 EFFILE
fileio.c:102:17: note: each undeclared identifier is reported only once for each function it appears in
fileio.c: In function 'copy':
fileio.c:378:17: error: 'DEFFILEMODE' undeclared (first use in this function); did you mean 'EFFILE'?
  mode_t fmode = DEFFILEMODE; /* XXX?? */
                 ^~~~~~~~~~~
                 EFFILE
make: *** [<builtin>: fileio.o] Error 1
```

I suspect I'm missing a development header, but I'm not sure where to find it and `./configure` didn't warn about its absence. On OpenBSD it seems to be defined in `sys/stat.h`. Is this maybe something that needs to be patched in the portable version?

I get the same error if I switch to the 6.5 release branch.

Thanks again!

**Comment by ibara** [comment]
Hi.

Can you try with the latest commit? It appears that musl libc doesn't have that define (at least, I can't find it). OpenBSD `sys/stat,h` and glibc `io/sys/stat.h` both agree on what the value of `DEFFILEMODE` should be: `0000666`, so I went with that.

**Comment by dgoerger** [comment]
Thanks! That did the trick. There are three other issues (I got it to compile and run with patches) but I'll open separate tickets so things don't get muddled.
