### ISSUE TITLE
Marking on macOS Terminal doesn't show selection

### ISSUE THREAD

**Issue by RobertoMachorro** [ibara/mg#32]
When performing marking on text (such as with CTL-space), I don't see a highlight/selection of any kind. However, I'm still able to kill the (invisible) selected text and then yank back successfully elsewhere. It works as expected, I just don't see the selection.

I realize that this may not be an issue with mg per-se, and that it just may be a terminal setting at my end. Any suggestions?

**Comment by ibara** [comment]
Hi --

That sounds like it could be an issue with your terminal emulator. Which terminal emulator are you using, and could you try some others? Most preferably, different terminal emulators with different backend handling code.

**Comment by RobertoMachorro** [comment]
I agree. Unfortunately it's the one that ships with macOS X. The name is actually "Terminal". I'm guessing that some CURSES escape codes aren't getting picked up... Emacs, me (MicroEmacs), etc do show the marking, but nothing is faster/lighter than **mg**.

This is how it defines itself:

```
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
```

I tried switching Terminfo to all of the following terminal declarations: xterm, vt102, rxvt, nsterm, dtterm, etc as well as enabling ANSI colors support, with no luck.

**Comment by ibara** [comment]
Can you download iTerm2 and try there? That would help narrow down possibilities.
It's free and available here: https://iterm2.com/

**Comment by ibara** [comment]
Oh... wait. I think I misread your initial report. mg doesn't highlight a mark. If you do CTRL-space it will report "Mark set" on the modeline but that's it.

I would happily take an extension if you want to write one to enable highlighting like that.

**Comment by RobertoMachorro** [comment]
Ah! That makes sense, and I did see the Mark set message. Thanks for the follow up!
