### ISSUE TITLE
Document lack of UTF-8 support more prominently, add missing word

### ISSUE THREAD

**Issue by pauamma** [ibara/mg#40]
Specifically:
- In README-Mg, mention it in "Known limitations".
- In mg.1, add "command" before "to alternate" in "Use the backup-to-home-directory to alternate between these two locations."
- in mg.1, move the last line, "Multi-byte character sets, such as UTF-8, are not supported.", to the start of the CAVEATS section, and maybe rename that section to "BUGS" or something stronger, as "CAVEATS" doesn't look strong enough for this to me.
No time for a pull request for now, but I will submit one time permitting unless someone beats me to it.

**Comment by ibara** [comment]
Hello --

I appreciate the concern, but a PR on those files won't be accepted in this repo. All three of those files are upstream files: they should be submitted directly to OpenBSD.

**Comment by pauamma** [comment]
> All three of those files are upstream files: they should be submitted directly to OpenBSD.

Done. (And sorry: I thought this repo *was* upstream.)
