### ISSUE TITLE
Compilation errors with GCC-14

### ISSUE THREAD

**Issue by nxhack** [ibara/mg#42]
Hi @ibara

I thank you for the work you do, it is very much appreciated.

I am porting your mg to OpenWrt. And I am the maintainer of that package.
https://github.com/openwrt/packages/tree/master/utils/mg
OpenWrt is now working on GCC-14 compliance.
OpenWrt (linux-6.1.89, musl-1.2.5)

I had the following error in mg.
```
main.c: In function 'pty_init':
main.c:311:9: error: implicit declaration of function 'login_tty' [-Wimplicit-function-declaration]
  311 |         login_tty(slave);
      |         ^~~~~~~~~
```
I have confirmed that this patch will resolve it.
```diff
--- a/main.c
+++ b/main.c
@@ -18,6 +18,7 @@
 #include <unistd.h>
 #if defined(__linux__) || defined(__CYGWIN__)
 #include <pty.h>
+#include <utmp.h>
 #elif defined(__OpenBSD__) || defined(__NetBSD__) || defined(__APPLE__)
 #include <util.h>
 #else
```

**Comment by ibara** [comment]
I am traveling at the moment, will fix when I return (or send a PR and I will merge). Thanks.

**Comment by nxhack** [comment]
Thank you!
