### ISSUE TITLE
No filename completion on cygwin

### ISSUE THREAD

**Issue by arturocastro** [ibara/mg#8]
Pressing tab always outputs "[No match]", i.e. after C-x C-f.

~~Also seems to affect CTAGS support.~~
It doesn't affect CTAGS at all, will post another issue for that.

Running on Babun/Win7.

**Comment by arturocastro** [comment]
The issue is that `NFILEN` is 1024 in `def.h:39`, but in cygwin, `MAXNAMLEN` is also 1024, so the condition in `fileio.c:495` is always met, ie. all paths are greater than `NFILEN - MAXNAMLEN`.

Increasing `NFILEN` solves the issue, but changing `MAXNAMLEN` for `NAME_MAX` (which has a value of 256 in cygwin) also works. The former solution increases memory use, of course.

Any of these changes would be simple, but please advise on what would be better, I can't test on all platforms right now. Once we figure it out, I can submit a pull request.

**Comment by kisom** [comment]
`NAME_MAX` is the POSIX definition (and `MAXNAMLEN` the BSD version of this), so I think it makes sense to swap out `MAXNAMLEN` for `NAME_MAX`.
