### ISSUE TITLE
ctags not working on Cygwin.

### ISSUE THREAD

**Issue by arturocastro** [ibara/mg#9]
tags file is parsed correctly, but either inserting the tag or retrieving it from the RBT is not working.

Babun/Win7 64

**Comment by ibara** [comment]
Not sure why I'm only seeing this now. But will look into it.

**Comment by ibara** [comment]
If you're still using Mg, could I trouble you to retest this now with the new code?

**Comment by ibara** [comment]
I'm closing this for now since it appears to work on my Cygwin setup.
If you're still having issues, please reopen.
